language: node_js

node_js:
  - "stable"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g istanbul
  - npm install -g karma

cache:
  directories:
    - node_modules

sudo: false
